---
language: ruby
cache: bundler
sudo: false
script: bundle exec rake test
before_install:
  - gem update bundler
  - gem update --system
rvm:
  - 2.4
  - 2.6
branches:
  only:
    - master
    - travis-ci
matrix:
  fast_finish: true
